[[redirects]]
from = "/*"
to = "public/html/index.html"
status = 200

[[redirects]]
from = "https://neon-lollipop-631625.netlify.app/submit-form"
to = "https://neon-lollipop-631625.netlify.app/confirmation_sendForm.html"
status = 200

